#ifndef INTERATIVIDADE_H_INCLUDED
#define INTERATIVIDADE_H_INCLUDED

/**PROTOTIPO DA FUN플O PARA EXIBIR O MENU PRINCIPAL*/
void exibe();

/**PROTOTIPO DA FUN플O PARA EXIBIR AS OP합ES DE ROUPAS PARA DOAR*/
void menuroupa();

/**PROTOTIPO DA FUN플O PARA EXIBIR O EFEITO DE LOADING*/
void load();

#endif // INTERATIVIDADE_H_INCLUDED
